apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
  labels:
    openshift.io/cluster-monitoring: 'true'
  name: {{ .Values.operator.namespace }}